### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/encoderPy#45]
Make sure the branches names are labelled meaningful things, if not it is hard to navigate and understand. Branches are really messy, should instead keep the branches for each function, and if anything, large needs to be changed. I see that this is implemented in terms of meaningful branch names for milestone 2's tasks, good job. Make sure the pull request are consistent and clear, such as making sure the headings are either capitalized or not.

**Comment by braydentang1** [comment]
Hey @andytai7, thanks for the valuable feedback. We have cleaned up our branches as you suggested in the lab session last Monday. We also improved our pull request titles so that they all follow a consistent grammar, and have edited the past ones we made.

Thank you!
