### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/encoderPy#51]
Great job, branch organization is great! Only group to do this so far. 
For the reviewing each other’s code, I don’t really see any pull requests that showed that some part of each team member’s code was reviewed by another peer, please add this, or if it is done, please make it clear who edited/reviewed who’s code. I think I see one in brown’s frequency encoder where Brayden edited training_data on encodeR? But please make the reviewing of code clear, or can explain to me in lab!

**Comment by braydentang1** [comment]
Thanks Andy. We have created an issue #62 that addresses this.
