### ISSUE TITLE
Pull request review

### ISSUE THREAD

**Issue by fsywang** [UBC-MDS/encoderPy#62]
This addresses the issue of milestone 2 feedback #51.

- Bronwyn reviews Brayden code (conjugate_encoder.R, [pull request 44 on R repo](https://github.com/UBC-MDS/encodeR/pull/44)).

- Brayden review Shiying's code (target_encoder.py, #43).

- Shiying reviews Robert's code (onehot_encoder.py, #46)

- Robert reviews Bronwyn's code (frequency_encoder.R, [pull request 43 on R repo](https://github.com/UBC-MDS/encodeR/pull/43)).

**Comment by braydentang1** [comment]
@andytai7 As requested, here are the code reviews that we all did.
