### ISSUE TITLE
Feedback from Alistair

### ISSUE THREAD

**Issue by braydentang1** [UBC-MDS/encoderPy#72]
As outlined [here:](https://github.com/UBC-MDS/software-review/issues/18#issuecomment-602099512)

- [x] Add semantic-versioning dependency to the README file so that users install this before trying to install the package.
- [x] Figure out how to show the output dataframe in the Python package. Honestly, don't really know how to do this in Python. Maybe switching to a pure .rmd file with reticulate makes more sense here (in fact it probably does, this would address Brendon's issues as well).
- [x] Fix the consistency in argument documentation so that we all have the same descriptions
- [x]  Add X_test = None to the onehot_encoder. 
- [x]  ~~Remove the actual call to the functions (this is probably not that necessary, it's just redundant code and so this should probably be low priority)~~
- [x] ~~Add more defensive coding. Target_encoder and conjugate_encoder seem sufficient. Frequency and onehot lack defensive exceptions IMO.~~
- [x] ~~Change defensive coding to not use exceptions and raise specific errors instead. This might be time consuming and it might be wise to forego this for now.~~

**Comment by bbaillie** [comment]
I used the @braydentang1 and @fsywang 's defensive code from their functions as a template for mine in frequency_encoder(). Not much applied to my function as it's functionality was very basic. What other defensive tests would you like to see?

**Comment by robilizando** [comment]
Essential Defensive coding for One-Hot Encoding is included within the code. like @bbaillie, I took @fsywang  and @braydentang1 as a template (for consistency) and selected essential for my function but do not list them all upfront. Allistar might have missed these when looking at the frequency and one-hot functions. I think we can tick this box too.

**Comment by fsywang** [comment]
- Regarding the feedback "remove the actual call to the functions", when we try to remove them, the code coverage will go down. Turns out poetry treated the test function as another condition to cover, so we decide to keep them.

- Regarding the feedback "change tests to not use exceptions and raise specific errors instead", this is a bit time consuming, so we decide to leave it for now.
